[package]
name = "libzeropool"
version = "0.4.1"
authors = ["Igor Gulamov <igor.gulamov@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fawkes-crypto = { version = "4.2.1", features = ["rand_support"] }
sha3 = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0"}
lazy_static = "1.4.0"
chacha20poly1305 = "0.8.0"

[dev-dependencies]
fawkes-crypto = { version = "4.2.1", features = ["rand_support", "backend_bellman_groth16"] }
