[package]
name = "libzeropool"
version = "0.1.0"
authors = ["Igor Gulamov <igor.gulamov@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fawkes-crypto = {path = "../fawkes-crypto"}
fawkes-crypto_derive = {version="0.2.2", path = "../fawkes-crypto/fawkes-crypto_derive"}
num = "0.2.1"
rand = "=0.4"
typenum = "=1.12.0"
async-trait = "0.1.30"

[dependencies.ff]
version = "=0.7"
features = ["derive"]
package = "ff_ce"

[dependencies.bellman]
version = "=0.3.1"
package = "bellman_ce"
default-features = false