[package]
name = "libzeropool"
version = "0.1.0"
authors = ["Igor Gulamov <igor.gulamov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fawkes-crypto = {path = "../fawkes-crypto"}

[dependencies.ff]
version = "=0.7"
features = ["derive"]
package = "ff_ce"