[package]
name = "libzeropool"
version = "0.2.0"
authors = ["Igor Gulamov <igor.gulamov@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fawkes-crypto = {version="3.0.4", features=["rand_support"]}
sha3 = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4.0"
crc = "1.8.1"